### ISSUE TITLE
Running log-replay

### ISSUE THREAD

**Issue by linkyndy** [Gonzih/log-replay#2]
It may be a stupid question, but how do I run `log-replay`? I've installed it with `go get`, but there is no executable. I tried to build `main.go` then, but it gives me some undefined errors.

**Comment by Gonzih** [comment]
Try adding $GOPATH/bin to your $PATH.

**Comment by linkyndy** [comment]
Thank you for your fast answer! It works.

**Comment by Gonzih** [comment]
Cool!
