### ISSUE TITLE
Providing a custom format

### ISSUE THREAD

**Issue by linkyndy** [Gonzih/log-replay#3]
My log format is a bit different than the default one. I tried providing a `--format` argument, but whatever I tried, I didn't succeed in making it work.

My log lines look like this:

```
0.0.0.0 - - [11/Jun/2017:02:00:00 +0200] "POST /path HTTP/1.1" 200 129 "https://www.example.com/path?gclid=CL7u8Iq-tNQC" "Mozilla/5.0 (Linux; Android 6.0.1; SAMSUNG SM-J700M Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/5.4 Chrome/51.0.2704.106 Mobile Safari/537.36"
```

I tried with these formats:

```
"$remote_addr $ident $auth [$time_local] \"$verb $request HTTP/$http\" $status $request_length \"$referrer\" \"$agent\""
```

```
"$remote_addr $ident $auth [$time_local] \"$verb $request HTTP/$http\" $status $request_length $referrer $agent"
```

```
"$remote_addr $ident $auth [$time_local] $verb $request HTTP/$http $status $request_length $referrer $agent"
```

```
'$remote_addr $ident $auth [$time_local] "$verb $request HTTP/$http" $status $request_length "$referrer" "$agent"'
```

Unfortunately, nothing worked (got just `Reached EOF` or `ERROR while parsing string: /path`). What am I doing wrong? How should the format parts be given/named? And how should the quotes/whitespace be handled?

**Comment by Gonzih** [comment]
If we are talking about nginx logs then I just use gonx library to parse logs, refer to https://github.com/satyrius/gonx documentation on their parser format.

**Comment by linkyndy** [comment]
Thanks for pointing me out. Also, what should the names of the variables be?

**Comment by Gonzih** [comment]
https://github.com/Gonzih/log-replay/blob/master/main.go#L50 those are default variable that are used.

**Comment by linkyndy** [comment]
That's my problem, my logs do not have values associated with all those variables; they also have some extra variables.

**Comment by Gonzih** [comment]
Everything extra will be ignored, skip ones that you dont have and try 
it out. I think path and time_local and request are ones that are used 
to schedule http calls currently. Everything rest does not matter 
really.  See here 
https://github.com/Gonzih/log-replay/blob/master/nginx.go#L56-L66
