### ISSUE TITLE
Allow a way to limit idle connections

### ISSUE THREAD

**Issue by dpryden** [Gonzih/log-replay#8]
Currently, it looks like `fireHTTPRequest` creates a new `http.Client` for every request, which is unnecessary. But I believe this is also responsible for leaking TCP connections. Since the client doesn't close the connection after making a request (since the default `Transport` caches connections for later use), on the server side (nginx in my case), when replaying 100 requests per second, I see 1000 or more idle connections (and this appears to scale up as I increase load). At a high enough level of load, I hit nginx's `worker_connections` limit, and nginx stops being able to receive new connections, even though the server has capacity to serve them.

I see a couple of ways to resolve this: one way would be to simply create the `http.Client` in `mainLoop` instead and share it with all the goroutines. This seems like it would probably be the simplest solution.

On the other hand, there may be value in allowing a user to customize the `http.Transport` being used, especially the `MaxIdleConns` and `IdleConnTimeout` settings. If I could control those, either for a single `http.Client` or for each client, that would resolve this issue as well.

If you are interested, I could try to put together a pull request.

**Comment by Gonzih** [comment]
Hey, pull requests are always welcome! Sounds like you have good understanding of a problem and solution in mind, so i would say - just go for it ;)
